### ISSUE TITLE
Link generator for addreses is broken

### ISSUE THREAD

**Issue by stefanverhoeff** [heremaps/map-linkbuilder-app#3]
Generating a link for an address on [1] doesn't work. The JS console shows an error:
`Failed to load resource: the server responded with a status of 403 (Forbidden)
builder.js:147 Uncaught TypeError: Cannot read property 'items' of undefined
    at here.builder.LocationBox._handleRequest (builder.js:147)
    at XMLHttpRequest.ajax.onload (utils.js:18)`

The Places API link gives a 403 Not authorized error:
https://places.api.here.com/places/v1/discover/search?app_id=45vC3JHWu5fUqqUm9Ik2&app_code=U8WhuCuhmYAHgttfjOEdfg&X-Map-Viewport=-167.4317,-56.2974,-168.7692,74.4081&X-NOSE-nokiamaps-lookahead=1&q=Schreiberhauer%20Strasse%2011,%20Berlin,%20Germany

Perhaps the AppId is not valid?

Btw, I work for here. Get in touch at stefan.verhoeff@here.com

Cheers,
Stefan

[1] http://heremaps.github.io/map-linkbuilder-app/

**Comment by freethan** [comment]
Hey @stefanverhoeff thanks for bringing this to our attention. Stay tuned.

**Comment by stefanverhoeff** [comment]
Thanks! I'm tuned in.

**Comment by freethan** [comment]
A commit with a newer app_id and app_code pair was landed by @joecks  : https://github.com/heremaps/map-linkbuilder-app/commit/e768ea5223b1a2c990b0b2bc37abcdd588babf5f

@joecks Please take a look at the failing tests

**Comment by sschuberth** [comment]
@freethan How about disallowing direct pushes to force contributions to happen via PRs that are checked by Travis *before* things get merged?

**Comment by freethan** [comment]
@stefanverhoeff Are we ok to close this issue ?

**Comment by stefanverhoeff** [comment]
Yes can be closed. The linkbuilder works now. Thanks!
